
'use strict';
const $=id=>document.getElementById(id), KEY='sunset-guard-v2';
const heroes=[{id:'su',name:'장수연',role:'원거리',icon:'🤠',color:'#b76749',atk:17,hp:150,rate:.7,range:1050,desc:'리볼버 · 안정적인 연속 사격'},{id:'chel',name:'첼리',role:'원거리',icon:'👱‍♀️',color:'#d8ae53',atk:25,hp:120,rate:.5,range:1080,desc:'명사수 · 빠른 사격, 낮은 체력'},{id:'buck',name:'벅',role:'탱커',icon:'🛡️',color:'#779592',atk:13,hp:650,rate:1.3,range:145,desc:'둔기 · 주 대상 100%, 근접 범위의 다른 적에게 20% 피해'},{id:'rose',name:'로즈',role:'근거리',icon:'⚔️',color:'#b96568',atk:48,hp:300,rate:.8,range:165,desc:'검객 · 접근한 적에게 강력한 일격'},{id:'june',name:'준',role:'지원',icon:'🌿',color:'#8ba570',atk:9,hp:190,rate:1.1,range:850,desc:'의무병 · 2초마다 아군 회복, 공격력 +12%'},{id:'ash',name:'애쉬',role:'원거리',icon:'💣',color:'#947aad',atk:34,hp:130,rate:1.5,range:950,desc:'폭파병 · 기본 공격이 주변 적에게 피해'}];
const upgrades=[['화약 강화','공격력 +12%'],['속사 훈련','공격 간격 4% 단축'],['신속 장전','장전시간 6% 단축'],['정밀 조준','치명타 확률 +2%'],['관통 탄두','치명타 피해 +10%'],['확장 탄창','탄창 +1발'],['장거리 조준경','사거리 +25'],['생존 훈련','최대 체력 +15%'],['가죽 보강','피해 감소 +2%'],['야전 회복','초당 체력 회복 +0.7'],['생명 탄환','흡혈 +1%'],['사냥꾼 보상','처치 골드 +3%'],['보스 사냥','보스 피해 +8%'],['산탄 파편','주변 적 피해 +3%'],['냉기 탄환','감속 +2%'],['소이 탄환','초당 화상 피해 +5%'],['충격 탄환','기절 확률 +1%'],['추가 사격','2연타 확률 +2%'],['방벽 정비','마을 내구도 +35'],['수리 지원','마을 초당 회복 +0.2'],['결전 훈련','필살기 피해 +12%'],['필살기 가속','필살기 대기시간 4% 단축'],['응급 구조','부활 대기시간 5% 단축'],['역전의 한 발','체력 절반 이하일 때 피해 +6%']];
const items=[{id:'iron',name:'개척자의 리볼버',slot:'weapon',icon:'🔫',desc:'공격력 +15%',atk:.15},{id:'fire',name:'잿불 리볼버',slot:'weapon',icon:'🔥',desc:'공격력 +25% · 화상',atk:.25,fire:.15},{id:'ice',name:'서리 장총',slot:'weapon',icon:'❄️',desc:'공격력 +20% · 20% 감속',atk:.2,slow:.2},{id:'vest',name:'보안관 조끼',slot:'armor',icon:'🦺',desc:'체력 +30% · 피해 감소 8%',hp:.3,armor:.08},{id:'coat',name:'결투가의 코트',slot:'armor',icon:'🧥',desc:'체력 +15% · 치명타 확률 +8%',hp:.15,crit:.08},{id:'star',name:'황금 보안관 배지',slot:'charm',icon:'⭐',desc:'공격력 +10% · 처치 골드 +15%',atk:.1,gold:.15},{id:'herb',name:'치유의 부적',slot:'charm',icon:'🍀',desc:'초당 회복 +3 · 흡혈 +5%',regen:3,leech:.05}];
items.push({id:'mace',name:'개척자의 철퇴',slot:'weapon',desc:'탱커 전용 · 공격력 +25%',atk:.25},{id:'saber',name:'기병대 세이버',slot:'weapon',desc:'근거리 전용 · 공격력 +25%',atk:.25});
const fresh=()=>({version:2,town:[0,0,0,0],settings:{bgm:.3,sfx:.5},pity:0,session:true,wave:1,best:1,gold:600,gems:120,owned:['su'],slots:['su',null,null,null,null],levels:{su:Array(24).fill(0)},gear:{su:{}},inventory:['iron','vest'],saved:Date.now(),draws:0});
function migrate(p){
 if(p?.version===1){p=JSON.parse(JSON.stringify(p));p.version=2;p.town=[0,0,0,0];p.settings={bgm:.3,sfx:.5};p.pity=0;p.session=true;
 for(const id of p.owned||[]){p.town[0]+=p.levels[id][18]||0;p.town[1]+=p.levels[id][19]||0;p.levels[id][18]=0;p.levels[id][19]=0;}
 }return p;
}
let state=fresh(),storageOK=true,saveRecovery=false;
try{let raw=localStorage.getItem(KEY)||localStorage.getItem('sunset-guard-v1');if(raw){let p=migrate(JSON.parse(raw));if(!validate(p))throw Error('invalid save');state=p;}}
catch{saveRecovery=true;try{let b=migrate(JSON.parse(localStorage.getItem(KEY+'-backup')));if(validate(b))state=b;}catch{} }
let testMode=false,backup=null,selected='su',tab='영웅',speed=1,paused=false,enemies=[],effects=[],runtime={},spawned=0,killed=0,spawnTimer=0,phaseTimer=2,phase='start',baseHP=500,time=0,healTimer=0,uiTimer=0;
let detail=false,heroTab='성장',equipFilter='전체',lastFocus=null;
const isMelee=id=>['탱커','근거리'].includes(hero(id).role);
const money=n=>Math.floor(n).toLocaleString('ko-KR');const hero=id=>heroes.find(h=>h.id===id);const level=id=>state.levels[id]||Array(24).fill(0);
function stats(id){const h=hero(id),l=level(id),eq=Object.values(state.gear[id]||{}).map(i=>items.find(x=>x.id===i)).filter(Boolean),g=k=>eq.reduce((n,i)=>n+(i[k]||0),0);return {atk:h.atk*(1+l[0]*.12+g('atk')),hp:h.hp*(1+l[7]*.15+g('hp')+(isMelee(id)?l[5]*.03:0)),rate:Math.max(.12,h.rate/(1+l[1]*.04)),reload:2/(1+l[2]*.06),crit:Math.min(.8,.08+l[3]*.02+g('crit')),critD:1.6+l[4]*.1,mag:6+l[5],range:isMelee(id)?Math.min(220,h.range+l[6]*3):h.range+l[6]*25,armor:Math.min(.75,l[8]*.02+g('armor')),regen:l[9]*.7+g('regen')+(isMelee(id)?l[2]*.25:0),leech:Math.min(.5,l[10]*.01+g('leech')),gold:l[11]*.03+g('gold'),boss:l[12]*.08,splash:(id==='ash'?.4:0)+l[13]*.03,slow:Math.min(.7,l[14]*.02+g('slow')),fire:l[15]*.05+g('fire'),stun:Math.min(.5,l[16]*.01),double:Math.min(.7,l[17]*.02),ult:1+l[20]*.12+(id==='buck'?l[13]*.06:0),cd:18/(1+l[21]*.04),revive:10/(1+l[22]*.05),clutch:l[23]*.06};}
function baseMax(){return 500+state.town[0]*35}function townArmor(){return Math.min(.6,state.town[2]*.02)}
function actor(id){if(!runtime[id]){let s=stats(id);runtime[id]={hp:s.hp,max:s.hp,ammo:s.mag,cd:.2,reload:0,ult:s.cd,dead:0,flash:0}}return runtime[id]}
function save(){if(testMode||saveRecovery)return;state.saved=Date.now();try{const previous=localStorage.getItem(KEY);if(previous){try{if(validate(JSON.parse(previous)))localStorage.setItem(KEY+'-backup',previous)}catch{}}localStorage.setItem(KEY,JSON.stringify(state));$('saveStatus').textContent='● 자동 저장됨';}catch{storageOK=false;$('saveStatus').textContent='저장 불가 · 메뉴에서 저장파일 내보내기';}}
let toastTimer;function toast(t){$('toast').textContent=t;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2600)}
function chapter(){return Math.floor((state.wave-1)/100)}function total(){return 7+Math.min(13,Math.floor(state.wave/4))}function bossWave(){return state.wave%10===0}function resetWave(){enemies=[];effects=[];runtime={};spawned=0;killed=0;spawnTimer=.6;baseHP=baseMax();phase='fight';phaseTimer=0;healTimer=0;state.slots.filter(Boolean).forEach(actor);}
function spawn(){let boss=bossWave()&&spawned===total()-1,main=state.wave%100===0,scale=Math.pow(1.015,Math.min(state.wave-1,1000)),hp=(28+state.wave*3)*scale*(boss?(main?18:5):1);enemies.push({x:1470,y:326+Math.random()*175,hp,max:hp,damage:(5+state.wave*.35)*Math.pow(1.01,Math.min(state.wave-1,1000))*(boss?2:1),speed:27+Math.random()*15+(boss?-10:0),kind:spawned%3,boss,main,slow:0,burn:0,burnTime:0,stun:0,hit:0,attack:0});spawned++;}
function position(id){let i=state.slots.indexOf(id),front=['탱커','근거리'].includes(hero(id).role);return{x:front?470:300+(i%2)*42,y:315+i*44}}
function hit(e,damage,id,critical=false){if(e.hp<=0)return;e.hp-=damage;e.hit=.15;effects.push({type:'text',x:e.x,y:e.y-50,t:.7,text:(critical?'✦ ':'')+Math.ceil(damage),color:critical?'#ffe39b':'#fff3db'});if(e.hp<=0){killed++;state.gold+=(8+state.wave*2)*(1+stats(id).gold+state.town[3]*.03)*(e.boss?6:1);}}
function inReach(id,e){const p=position(id);return e.hp>0&&e.x>=p.x-25&&e.x-p.x<=stats(id).range}
function fire(id,e,ultimate=false){
 if(!e||!inReach(id,e))return;const s=stats(id),a=actor(id),p=position(id),melee=isMelee(id);
 a.flash=melee?.3:.14;
 effects.push(melee?{type:'swing',x:p.x,y:p.y-35,t:.3,color:ultimate?'#ffdc91':'#e9d6a7'}:{type:'line',x:p.x+25,y:p.y-22,ex:e.x,ey:e.y-15,t:.14,color:ultimate?'#ffa758':'#fff3b5'});
 playSfx(melee?'hit':'shot');
 const support=state.slots.includes('june')&&actor('june').hp>0?1.12:1;
 // Tank BASIC: exactly 100% attack on primary; 20% on every other living target in tank range. No bullet or reload path.
 if(id==='buck'&&!ultimate){const damage=s.atk*support;const others=enemies.filter(n=>n!==e&&inReach(id,n));hit(e,damage,id);others.forEach(n=>hit(n,damage*.2,id));applyStatus(e,s,id);a.hp=Math.min(s.hp,a.hp+damage*s.leech);return;}
 const crit=Math.random()<s.crit,damage=s.atk*support*(crit?s.critD:1)*(e.boss?1+s.boss:1)*(a.hp<s.hp/2?1+s.clutch:1)*(ultimate?4*s.ult:1);
 hit(e,damage,id,crit);if(s.double>Math.random()&&e.hp>0)hit(e,damage*.7,id);
 a.hp=Math.min(s.hp,a.hp+damage*s.leech);
 if(s.splash||id==='buck')enemies.filter(n=>n!==e&&n.hp>0&&(melee?inReach(id,n):Math.abs(n.x-e.x)<120)).forEach(n=>hit(n,damage*(id==='buck'?.2:Math.min(1,s.splash)),id));
 applyStatus(e,s,id);
}
function applyStatus(e,s,id){e.slow=s.slow;e.burn=s.atk*s.fire;e.burnTime=3;e.owner=id;if(Math.random()<s.stun)e.stun=.8;}
function update(dt){time+=dt;effects.forEach(e=>{e.t-=dt;if(e.type==='text')e.y-=dt*25});effects=effects.filter(e=>e.t>0);if(phase!=='fight'){phaseTimer-=dt;if(phaseTimer<=0)resetWave();return}spawnTimer-=dt;if(spawned<total()&&spawnTimer<=0){spawn();spawnTimer=.9}let active=state.slots.filter(Boolean);for(let id of active){let a=actor(id),s=stats(id);if(s.hp!==a.max){a.hp=Math.min(s.hp,a.hp+Math.max(0,s.hp-a.max));a.max=s.hp}a.flash=Math.max(0,a.flash-dt);if(a.hp<=0){a.dead-=dt;if(a.dead<=0){a.hp=s.hp;a.ammo=s.mag}continue}a.hp=Math.min(s.hp,a.hp+s.regen*dt);a.cd-=dt;a.ult-=dt;if(a.reload>0){a.reload-=dt;if(a.reload<=0)a.ammo=s.mag;continue}let p=position(id),target=enemies.filter(e=>e.hp>0&&e.x>=p.x-25&&e.x-p.x<=s.range).sort((a,b)=>a.x-b.x)[0];if(target&&a.cd<=0){fire(id,target);a.cd=s.rate;if(!isMelee(id)){a.ammo--;if(a.ammo<=0)a.reload=s.reload}}if(target&&a.ult<=0){fire(id,target,true);a.ult=s.cd}}
healTimer+=dt;if(healTimer>=2){healTimer=0;if(active.includes('june')&&actor('june').hp>0)active.forEach(id=>{let a=actor(id);if(a.hp>0)a.hp=Math.min(stats(id).hp,a.hp+stats('june').atk*.9)})}baseHP=Math.min(baseMax(),baseHP+state.town[1]*.2*dt);
for(let e of enemies){if(e.hp<=0)continue;e.hit=Math.max(0,e.hit-dt);e.stun-=dt;if(e.burnTime>0){e.burnTime-=dt;if(e.burn>0)hitBurn(e,e.burn*dt)}if(e.hp<=0||e.stun>0)continue;let block=active.filter(id=>actor(id).hp>0&&Math.abs(e.x-position(id).x)<48).sort((a,b)=>position(b).x-position(a).x)[0];if(block){e.attack-=dt;if(e.attack<=0){let a=actor(block);a.hp-=e.damage*(1-stats(block).armor);e.attack=.9;if(a.hp<=0)a.dead=stats(block).revive}}else if(e.x<=185){baseHP-=e.damage*(1-townArmor())*dt}else e.x-=e.speed*(1-e.slow)*dt;}
enemies=enemies.filter(e=>e.hp>0);if(baseHP<=0){baseHP=0;phase='fail';phaseTimer=3;save();return}if(spawned===total()&&!enemies.length){let reward=40+state.wave*10;state.gold+=reward;state.gems+=bossWave()?20:2;state.wave++;state.best=Math.max(state.best,state.wave);phase='clear';phaseTimer=2.5;playSfx('clear');if(state.wave%10===1&&state.wave>1){let it=items[Math.floor(Math.random()*items.length)];if(!state.inventory.includes(it.id)){state.inventory.push(it.id);toast('보스 전리품: '+it.name)}}save();renderPanel();}}
function hitBurn(e,d){e.hp-=d;if(e.hp<=0){killed++;state.gold+=(8+state.wave*2)*(1+stats(e.owner||'su').gold+state.town[3]*.03)*(e.boss?6:1)}}
const c=$('canvas'),ctx=c.getContext('2d');function rect(x,y,w,h,color){ctx.fillStyle=color;ctx.fillRect(x,y,w,h)}function poly(points,color){ctx.fillStyle=color;ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.closePath();ctx.fill()}function ellipse(x,y,rx,ry,color){ctx.fillStyle=color;ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,7);ctx.fill()}function label(t,x,y,size,color){ctx.fillStyle=color;ctx.font=`${size}px "Noto Sans KR",system-ui`;ctx.textAlign='center';ctx.fillText(t,x,y)}
const assetsReady=true;$('assetStatus').hidden=true;
function imageAt(id,x,y,w,h){ctx.save();ctx.translate(x,y);ctx.scale(w/360,h/150);PixelArt.background(ctx,Number(id.slice(2))%3);ctx.restore()}
function drawHero(id,x,y){const a=actor(id);ctx.save();ctx.translate(Math.round(x/4)*4,Math.round(y/4)*4);if(a.hp<=0)ctx.globalAlpha=.3;ctx.save();ctx.scale(3,3);ctx.translate(-20,-36);PixelArt.hero(ctx,id,a.flash>0,time);ctx.restore();rect(-25,16,50,4,'#263435');rect(-25,16,50*Math.max(0,a.hp/stats(id).hp),4,'#b5d5b4');if(a.hp<=0)label(Math.ceil(a.dead)+'s',0,-52,13,'#f2d6a2');else if(a.reload>0)label('장전',0,33,10,'#fff0c9');ctx.restore()}
function enemyArt(e){return chapter()%3===0?['boar','wolf','cat'][e.kind]:chapter()%3===1?'caveman':'zombie'}
function drawEnemy(e){const size=e.boss?(e.main?4.4:3.3):2.5,h=37*size;ctx.save();ctx.translate(Math.round(e.x/4)*4,Math.round(e.y/4)*4);ctx.save();ctx.scale(size,size);ctx.translate(-18,-36);if(e.hit>0)ctx.globalAlpha=.65;PixelArt.enemy(ctx,enemyArt(e),time+e.y,e.boss);ctx.restore();if(e.boss)label(e.main?'MAIN BOSS':'ELITE',0,-h-14,10,'#ffe1a0');rect(-27,-h-5,54,4,'#16252a');rect(-27,-h-5,54*Math.max(0,e.hp/e.max),4,e.boss?'#ebbb77':'#c58172');if(e.burnTime>0&&e.burn)label('♨',20,-h/2,16,'#ffb251');ctx.restore()}

function draw(){ctx.clearRect(0,0,1440,600);imageAt('bg'+chapter()%3,0,0,1440,600);ctx.fillStyle='#07181b12';ctx.fillRect(0,0,1440,600);let actors=state.slots.filter(Boolean).map(id=>({y:position(id).y,draw:()=>{let p=position(id);drawHero(id,p.x,p.y)}}));enemies.forEach(e=>actors.push({y:e.y,draw:()=>drawEnemy(e)}));actors.sort((a,b)=>a.y-b.y).forEach(x=>x.draw());effects.forEach(e=>{ctx.globalAlpha=Math.min(1,e.t*6);if(e.type==='line'){ctx.strokeStyle=e.color;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(e.x,e.y);ctx.lineTo(e.ex,e.ey);ctx.stroke()}else if(e.type==='swing'){ctx.strokeStyle=e.color;ctx.lineWidth=5;ctx.beginPath();ctx.arc(e.x,e.y,70,-1,1);ctx.stroke()}else label(e.text,e.x,e.y,16,e.color)});ctx.globalAlpha=1}

function hud(){PixelArt.paint();let ch=chapter(),names=['붉은 모래의 개척지','잊힌 원시의 협곡','안개에 잠긴 무덤'],eng=['THE WILDS','ANCIENT CANYON','DEAD FRONTIER'];$('region').textContent=names[ch%3]+(ch>=3?' · '+(Math.floor(ch/3)+1)+'주기':'');$('chapter').textContent=`CHAPTER ${String(ch+1).padStart(2,'0')} / ${eng[ch%3]}`;$('gold').textContent=money(state.gold);$('gems').textContent=money(state.gems);$('wave').textContent=`WAVE ${String(state.wave).padStart(2,'0')}`+(bossWave()?(state.wave%100===0?' · 메인 보스':' · 중간 보스'):'');$('hptext').textContent=`${Math.ceil(baseHP)} / ${baseMax()}`;$('hpbar').style.width=Math.max(0,baseHP/baseMax()*100)+'%';$('wavebar').style.width=killed/total()*100+'%';$('progress').textContent=`${killed} / ${total()}`;$('phase').textContent=paused?'일시정지':phase==='clear'?'WAVE CLEAR · 다음 웨이브 준비':phase==='fail'?'방어 실패 · 같은 웨이브 재도전':phase==='start'?'마을을 지켜주세요':'';$('count').textContent=state.slots.filter(Boolean).length+' / 5 배치';}
// Canvas pixel art is shared by the battlefield and management screens.
const menuEntries=[['영웅','HEROES','M12 3a4 4 0 1 0 0 8 4 4 0 0 0 0-8M4 21v-3a8 8 0 0 1 16 0v3'],['마을 강화','TOWN UPGRADE','M3 11 12 3l9 8M5 10v11h14V10M9 21v-7h6v7'],['장비','EQUIPMENT','m8 3 4 3 4-3 5 5-4 4v9H7v-9L3 8Z'],['전투 배치','FORMATION','M3 3h6v6H3ZM15 3h6v6h-6ZM3 15h6v6H3ZM15 15h6v6h-6Z'],['상점','TRADING POST','M3 8h18l-2-5H5ZM4 8v13h16V8M9 21v-7h6v7'],['설정','SETTINGS','M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8M12 2v3M12 19v3M2 12h3M19 12h3M5 5l2 2M17 17l2 2M5 19l2-2M17 7l2-2']];
const imageTag=(id,cls='',alt='')=>`<canvas class="pixel-art ${cls}" data-pixel="${id}" width="${id.startsWith('bg')?360:144}" height="${id.startsWith('bg')?150:126}" role="img" aria-label="${alt||id}"></canvas>`;
const slotNames={weapon:'무기',armor:'방어구',charm:'장신구'};
let lastResult=null;
function power(id){const s=stats(id),uptime=isMelee(id)?1:(s.mag*s.rate)/(s.mag*s.rate+s.reload);return Math.round(s.atk/s.rate*uptime*(1+s.crit*(s.critD-1))*10+s.hp*(1+s.armor)*.25+s.regen*5)}
function sortedHeroes(){return [...heroes].sort((a,b)=>Number(state.owned.includes(b.id))-Number(state.owned.includes(a.id))||(state.owned.includes(a.id)?power(b.id)-power(a.id):0)||heroes.indexOf(a)-heroes.indexOf(b))}
function renderSquad(){$('squad').innerHTML=state.slots.map((id,i)=>`<button class="slot" data-slot="${i}" aria-label="${i+1}번 ${id?hero(id).name:'빈 슬롯'}"><em>0${i+1}</em>${id?imageTag(id,'',hero(id).name):'<div class="empty-icon">＋</div>'}<div><strong>${id?hero(id).name:'빈 배치'}</strong><small>${id?hero(id).role:'영웅 배치'}</small>${id?`<small class="power">전투력 ${money(power(id))}</small>`:''}</div></button>`).join('')}
function open(t='영웅'){tab=t;detail=false;lastFocus=document.activeElement;$('drawer').hidden=false;$('scrim').hidden=false;$('drawer').classList.add('open');$('quickMenu').hidden=true;$('menuToggle').setAttribute('aria-expanded','false');renderPanel();$('close').focus()}
function closePanel(){$('drawer').hidden=true;$('scrim').hidden=true;$('drawer').classList.remove('open');lastFocus?.focus?.()}
function selectHero(id){if(!state.owned.includes(id)){toast('해당 영웅을 아직 모집하지 않았습니다.');return false}selected=id;detail=true;heroTab='성장';renderPanel();return true}
function cost(i){return Math.ceil((22+i*4)*Math.pow(1.16,Math.min(500,level(selected)[i])))}
function townCost(i){return Math.ceil((80+i*60)*Math.pow(1.18,Math.min(500,state.town[i])))}
function heroSelect(){return `<label class="dim" for="character">장비를 관리할 영웅</label><select class="charselect" id="character">${sortedHeroes().filter(h=>state.owned.includes(h.id)).map(h=>`<option value="${h.id}" ${h.id===selected?'selected':''}>${h.name} · ${h.role} · 전투력 ${money(power(h.id))}</option>`).join('')}</select>`}
function gearSlots(){return `<div class="equipment-slots">${Object.entries(slotNames).map(([k,n])=>{const it=items.find(x=>x.id===state.gear[selected]?.[k]);return `<div class="equipment-slot"><small>${n}</small>${it?imageTag(it.id):'<div style="height:48px;line-height:48px;color:#637271">＋</div>'}${it?it.name:'미착용'}</div>`}).join('')}</div>`}
function gearInventory(){const group=items.filter(it=>state.inventory.includes(it.id)&&(equipFilter==='전체'||slotNames[it.slot]===equipFilter));return `<div class="filters">${['전체','무기','방어구','장신구'].map(x=>`<button data-filter="${x}" class="${x===equipFilter?'active':''}">${x}</button>`).join('')}</div>`+group.map(it=>{const owner=state.owned.find(id=>Object.values(state.gear[id]||{}).includes(it.id)),compatible=canEquip(selected,it);return `<div class="row">${imageTag(it.id,'',it.name)}<div class="grow"><strong>${it.name}</strong><p>${it.desc}</p><span class="dim">${owner?hero(owner).name+' 착용 중':'보유 · 미착용'}${compatible?'':' · 무기 유형 불일치'}</span></div><button data-equip="${it.id}" ${compatible?'':'disabled'}>${owner===selected?'해제':owner?'이전 착용':'착용'}</button></div>`}).join('')||'<p class="dim">해당 장비가 없습니다. 상점에서 보급 상자를 열어보세요.</p>'}
function upgradeInfo(i){let u=[...upgrades[i]];if(isMelee(selected)){const m={0:['무기 연마','공격력 +12%'],1:['공격 훈련','공격 간격 4% 단축'],2:['호흡 회복','초당 체력 회복 +0.25'],3:['결전 집중','치명타 확률 +2% · 탱커는 필살기에 적용'],4:['치명 일격','치명타 피해 +10% · 탱커는 필살기에 적용'],5:['전투 체력','최대 체력 +3%'],6:['보법 훈련','근접 사거리 +3 · 최대 220'],12:['보스 사냥',selected==='buck'?'보스에게 필살기 피해 +8%':'보스 피해 +8%'],13:['파쇄 충격',selected==='buck'?'필살기 피해 +6%':'주변 적 피해 +3%'],17:['연격 수련',selected==='buck'?'필살기 추가 타격 확률 +2%':'추가 타격 확률 +2%'],23:['역전의 일격',selected==='buck'?'체력 절반 이하일 때 필살기 피해 +6%':'체력 절반 이하일 때 피해 +6%']};if(m[i])u=m[i]}return u}
function heroDetail(){const h=hero(selected),s=stats(selected),lv=level(selected).reduce((n,v)=>n+v,0),eq=Object.values(state.gear[selected]||{});let html=`<button class="textbtn" data-action="backHeroes">← 전체 영웅</button><div class="hero-profile">${imageTag(selected,'',h.name)}<div><span class="eyebrow">${h.role} / DEFENDER</span><h2>${h.name}</h2><div class="cp">전투력 ${money(power(selected))}</div><p>${h.desc}</p></div></div><div class="status-summary"><div class="summary-card"><small>업그레이드 상태</small><strong>누적 강화 ${lv}회</strong><small>공격 Lv.${level(selected)[0]} · 체력 Lv.${level(selected)[7]}</small></div><div class="summary-card"><small>장비 착용 상태</small><strong>${eq.length} / 3 부위</strong><div class="gear-summary">${eq.map(id=>imageTag(id,'',items.find(x=>x.id===id).name)).join('')||'<span class="dim">착용 장비 없음</span>'}</div></div></div><div class="subtabs">${['성장','장착 장비','능력치'].map(t=>`<button data-hero-tab="${t}" class="${heroTab===t?'active':''}">${t}</button>`).join('')}</div>`;
if(heroTab==='장착 장비')return html+gearSlots()+gearInventory();if(heroTab==='능력치')return html+`<div class="stats">${[['공격력',s.atk.toFixed(1)],['최대 체력',Math.round(s.hp)],['공격 간격',s.rate.toFixed(2)+'초'],['사거리',s.range],['치명타 확률',Math.round(s.crit*100)+'%'],['치명타 배율',s.critD.toFixed(1)+'배'],['피해 감소',Math.round(s.armor*100)+'%'],['초당 회복',s.regen.toFixed(2)],['흡혈',Math.round(s.leech*100)+'%'],['필살기 대기',s.cd.toFixed(1)+'초'],[isMelee(selected)?'공격 방식':'탄창',isMelee(selected)?'근접 · 장전 없음':s.mag+'발'],['역할',h.role]].map(([k,v])=>`<div class="stat"><small>${k}</small>${v}</div>`).join('')}</div><p class="help">전투력은 공격·체력·방어·회복을 합산한 비교 지표입니다. 실제 전투 결과는 역할·사거리·지원 효과에 따라 달라집니다.</p>`;
html+=`<p class="notice">${selected==='buck'?'기본 공격: 주 대상 100% / 범위 내 나머지 적 20%. 총알과 장전은 사용하지 않습니다.':'강화는 선택한 영웅에게만 적용됩니다.'} 마을 내구도와 수리는 마을 강화에서 관리합니다.</p>`;
for(const [title,ids] of [['공격 훈련',[0,1,2,3,4,5,6]],['생존과 보상',[7,8,9,10,11]],['특수 효과',[12,13,14,15,16,17]],['필살기와 회복',[20,21,22,23]]]){html+=`<h3 class="group-title">${title}</h3>`+ids.map(i=>{let u=upgradeInfo(i);return `<div class="row"><div class="grow"><strong>${u[0]} <span class="badge">Lv.${level(selected)[i]}</span></strong><p>${u[1]}</p></div><button data-up="${i}" data-cost="${cost(i)}" ${state.gold<cost(i)?'disabled':''}>◈ ${money(cost(i))}</button></div>`}).join('')}return html}
function renderPanel(){if($('drawer').hidden)return;const entry=menuEntries.find(x=>x[0]===tab);$('panelTitle').textContent=tab;$('panelEnglish').textContent=entry?.[1]||'';let html='';if(tab==='영웅'){if(detail)html=heroDetail();else{let list=sortedHeroes(),card=h=>{let own=state.owned.includes(h.id);return `<button class="hero-card ${own?'':'locked'}" data-hero="${h.id}" aria-label="${h.name} ${own?'보유':'미보유'}"><div class="art">${imageTag(h.id,'',h.name)}<span class="locktag">${own?h.role:'미보유'}</span></div><div class="cardtext"><strong>${h.name}</strong><small>${h.role}</small><div class="power">${own?'전투력 '+money(power(h.id)):'모집 후 확인 가능'}</div></div></button>`};html=`<div class="sectionline"><strong>보유 영웅 <span class="badge">${state.owned.length} / ${heroes.length}</span></strong><small>전투력 높은 순</small></div><div class="hero-grid">${list.filter(h=>state.owned.includes(h.id)).map(card).join('')}</div>`;if(state.owned.length<heroes.length)html+=`<div class="sectionline sectionspace"><strong>아직 만나지 못한 영웅</strong><small>상점에서 모집</small></div><div class="hero-grid">${list.filter(h=>!state.owned.includes(h.id)).map(card).join('')}</div>`}}
if(tab==='장비')html=`<p class="notice">보유 장비를 종류별로 확인하고 영웅에게 착용하세요. 다른 영웅의 장비를 이전하면 기존 영웅에서는 해제됩니다.</p>`+heroSelect()+gearSlots()+gearInventory();
if(tab==='마을 강화')html=`${imageTag('bg0','town-art','서부마을')}<div class="stats"><div class="stat"><small>현재 / 최대 내구도</small><span id="townLiveHP">${Math.ceil(baseHP)}</span> / ${baseMax()}</div><div class="stat"><small>마을 피해 감소</small>${Math.round(townArmor()*100)}%</div><div class="stat"><small>초당 자동 수리</small>${(state.town[1]*.2).toFixed(1)}</div><div class="stat"><small>추가 처치 보상</small>+${state.town[3]*3}%</div></div><p class="notice">마을 강화는 모든 배치에 영구 적용됩니다. 기존 영웅의 방벽·수리 강화는 마을 강화로 이전되었습니다.</p>`+[['방벽 증축','최대 내구도 +35'],['수리 공방','초당 내구도 회복 +0.2'],['방어 설비','마을 피해 감소 +2% · 최대 60%'],['교역소','처치 골드 +3%']].map(([n,d],i)=>`<div class="row"><div><strong>${n}<span class="badge">Lv.${state.town[i]}</span></strong><p>${d}</p></div><button data-town="${i}" data-cost="${townCost(i)}" ${state.gold<townCost(i)||(i===2&&state.town[i]>=30)?'disabled':''}>${i===2&&state.town[i]>=30?'최대 강화':'◈ '+money(townCost(i))}</button></div>`).join('');
if(tab==='전투 배치')html=`<p class="notice">영웅 아래 슬롯 번호를 눌러 배치하세요. 배치된 영웅끼리는 위치를 교환합니다. 전방은 탱커·근거리, 후방은 원거리·지원입니다.</p><div class="formation">${state.slots.map((id,i)=>`<button class="form-slot" data-form-slot="${i}" style="left:${id&&isMelee(id)?65:20+(i%2)*17}%;top:${8+i*24}px" aria-label="${i+1}번 ${id?hero(id).name:'빈 슬롯'}">${id?imageTag(id,'',hero(id).name):'＋'}<small>${i+1}</small></button>`).join('')}</div>`+sortedHeroes().filter(h=>state.owned.includes(h.id)).map(h=>`<div class="row" style="display:block"><div style="display:flex;align-items:center;gap:12px">${imageTag(h.id,'',h.name)}<div><strong>${h.name} · ${h.role}</strong><p>전투력 ${money(power(h.id))} · ${state.slots.includes(h.id)?(state.slots.indexOf(h.id)+1)+'번 배치 중':'대기 중'}</p></div></div><div class="deploy">${state.slots.map((x,i)=>`<button data-place="${h.id}:${i}" class="${x===h.id?'active':''}">${i+1}번</button>`).join('')}<button data-remove="${h.id}" ${!state.slots.includes(h.id)||state.slots.filter(Boolean).length<2?'disabled':''}>해제</button></div></div>`).join('');
if(tab==='상점')html=`<div class="shop-banner"><div class="eyebrow">FRONTIER RECRUITMENT</div><h2>A new face in town.</h2><p>마을을 함께 지킬 새로운 동료를 만나세요.</p></div>${lastResult?`<div class="result-card">${lastResult.asset?imageTag(lastResult.asset):''}<strong>${lastResult.title}</strong><span class="dim">${lastResult.desc}</span></div>`:''}<div class="row"><div><strong>영웅 모집</strong><p>10회 이내 미보유 영웅 확정 · ${state.pity}/10</p></div><button class="primary" data-buy="hero" data-gem-cost="50" ${state.gems<50?'disabled':''}>✧ 50</button></div><div class="row"><div><strong>장비 보급 상자</strong><p>무기 · 방어구 · 장신구</p></div><button data-buy="gear" data-cost="250" ${state.gold<250?'disabled':''}>◈ 250</button></div><div class="row"><div><strong>보석 50개 교환</strong><p>전투 골드로 교환 · 실제 결제 없음</p></div><button data-buy="gem" data-cost="500" ${state.gold<500?'disabled':''}>◈ 500</button></div><details><summary>모집 확률과 중복 보상</summary><p class="help">일반 모집: 영웅 6종 각 1/6(약 16.67%). 미보유 영웅을 얻으면 확정 카운트가 초기화됩니다. 9회 연속 중복 이후 다음 모집은 남은 미보유 영웅 중 동일 확률입니다. 모두 보유했다면 일반 확률을 유지합니다.<br>중복 영웅: 200골드. 장비 ${items.length}종 각 1/${items.length}. 중복 장비: 120골드.<br>소모와 결과는 즉시 저장됩니다.</p></details>`;
if(tab==='설정')html=`<h3 style="margin-top:0">사운드</h3><p class="dim">화면을 누른 뒤 소리가 재생됩니다.</p>${['bgm','sfx'].map(k=>`<div class="row setting"><label>${k==='bgm'?'배경음':'효과음'} <output id="${k}Value">${Math.round(state.settings[k]*100)}%</output><input type="range" min="0" max="100" value="${state.settings[k]*100}" data-volume="${k}" aria-label="${k==='bgm'?'배경음':'효과음'} 볼륨"></label></div>`).join('')}<h3>계정</h3><div class="row"><div><strong>게스트 플레이</strong><p>진행 기록은 이 브라우저에 저장됩니다.</p></div><button data-action="linkAccount">계정 연동</button></div><p class="notice">계정 연동은 아직 지원하지 않습니다. 기기 간 이동은 아래 저장파일 내보내기·불러오기를 사용하세요.</p><button data-action="logout">로그아웃 · 로컬 세션 종료</button><h3>진행 기록</h3><p class="dim">최고 도달 ${state.best} 웨이브 · ${testMode?'테스트 모드: 본 진행에 저장하지 않음':'10초마다 자동 저장'}</p>${saveRecovery?'<p class="notice">저장 오류가 감지되어 덮어쓰기를 중단했습니다. 현재 기록을 내보낸 후 정상 저장파일을 불러오세요.</p>':''}<button data-action="export">저장파일 내보내기</button> <button data-action="import">불러오기</button><input type="file" id="importfile" accept="application/json" hidden><details><summary>프로토타입 테스트</summary><p class="help">본 진행을 보존하는 독립 테스트입니다.</p><div class="testgrid">${[1,10,100,101,200,201].map(w=>`<button data-test="${w}">${w} 웨이브</button>`).join('')}</div>${testMode?'<p><button class="primary" data-action="exitTest">본 진행으로 돌아가기</button></p>':''}</details><details><summary>플레이 안내</summary><p class="help">성공 시 다음 웨이브, 실패 시 같은 웨이브를 자동 반복합니다.<br>10웨이브 중간 보스 / 100웨이브 메인 보스.<br>동물 → 원시인 → 좀비 지역을 100웨이브마다 전환합니다.<br>탭을 숨기거나 세션을 종료하면 전투와 음악이 멈춥니다.<br>Space: 일시정지 / Esc: 팝업 닫기.<br>현재 버전은 결제와 서버 계정 기능이 없는 개발 버전입니다.</p></details>`;
const scroll=$('content').scrollTop;$('content').innerHTML=html;$('content').scrollTop=scroll;PixelArt.paint();refreshLiveUI()}
function refreshLiveUI(){$('panelGold').textContent=money(state.gold);$('panelGems').textContent=money(state.gems);document.querySelectorAll('[data-cost]').forEach(b=>{b.disabled=state.gold<Number(b.dataset.cost)||(b.dataset.town==='2'&&state.town[2]>=30)});document.querySelectorAll('[data-gem-cost]').forEach(b=>b.disabled=state.gems<Number(b.dataset.gemCost));const hp=$('townLiveHP');if(hp)hp.textContent=Math.ceil(baseHP)}
function changed(){renderSquad();renderPanel();save();hud()}
function place(id,i){if(!state.owned.includes(id)||!Number.isInteger(i)||i<0||i>4)return;let prev=state.slots.indexOf(id),old=state.slots[i];if(prev>=0)state.slots[prev]=old;state.slots[i]=id;actor(id);changed();toast(hero(id).name+' · '+(i+1)+'번 배치')}
function removeHero(id){let i=state.slots.indexOf(id);if(i>=0&&state.slots.filter(Boolean).length>1){state.slots[i]=null;changed()}else toast('최소 한 명의 수비대원이 필요합니다.')}
function canEquip(id,it){if(it.slot!=='weapon')return true;if(id==='buck')return it.id==='mace';if(id==='rose')return it.id==='saber';return !['mace','saber'].includes(it.id)}
function equip(item){let it=items.find(x=>x.id===item);if(!it||!state.inventory.includes(item)||!state.owned.includes(selected)||!canEquip(selected,it))return;let eq=state.gear[selected]||(state.gear[selected]={});if(eq[it.slot]===item)delete eq[it.slot];else{state.owned.forEach(id=>{if(state.gear[id]?.[it.slot]===item)delete state.gear[id][it.slot]});eq[it.slot]=item}changed()}
function upgrade(i){if(!Number.isInteger(i)||i<0||i>23||i===18||i===19||level(selected)[i]>=500)return;let c=cost(i);if(state.gold>=c){state.gold-=c;state.levels[selected][i]++;changed();playSfx('upgrade')}}
function upgradeTown(i){if(!Number.isInteger(i)||i<0||i>3||state.town[i]>=500||(i===2&&state.town[i]>=30))return;let c=townCost(i);if(state.gold>=c){state.gold-=c;state.town[i]++;if(i===0)baseHP+=35;changed();playSfx('upgrade')}}
function buy(kind){if(kind==='hero'&&state.gems>=50){state.gems-=50;state.draws++;let missing=heroes.filter(h=>!state.owned.includes(h.id)),pool=state.pity>=9&&missing.length?missing:heroes,h=pool[Math.floor(Math.random()*pool.length)];if(state.owned.includes(h.id)){state.gold+=200;state.pity=missing.length?state.pity+1:0;lastResult={asset:h.id,title:h.name+' · 중복 모집',desc:'200골드로 전환했습니다.'}}else{state.owned.push(h.id);state.levels[h.id]=Array(24).fill(0);state.gear[h.id]={};state.pity=0;lastResult={asset:h.id,title:h.name+' 합류',desc:'전투 배치에서 슬롯을 선택하세요.'}}playSfx('clear')}
else if(kind==='gear'&&state.gold>=250){state.gold-=250;let it=items[Math.floor(Math.random()*items.length)],duplicate=state.inventory.includes(it.id);if(duplicate)state.gold+=120;else state.inventory.push(it.id);lastResult={asset:it.id,title:it.name,desc:duplicate?'중복 장비 · 120골드 전환':it.desc};playSfx('upgrade')}
else if(kind==='gem'&&state.gold>=500){state.gold-=500;state.gems+=50;toast('50보석 교환 완료')}else return;changed()}
function test(w){if(![1,10,100,101,200,201].includes(w))return;if(!testMode){save();backup=JSON.parse(JSON.stringify(state));testMode=true}const settings={...state.settings};state=fresh();state.settings=settings;state.wave=w;state.best=w;state.gold=1e7;state.gems=5000;state.owned=heroes.map(h=>h.id);state.inventory=items.map(i=>i.id);state.slots=['su','chel','buck','rose','june'];state.owned.forEach(id=>{state.levels[id]=Array(24).fill(0);state.gear[id]={}});selected='su';resetWave();changed();toast('독립 테스트 · '+w+' 웨이브')}
function action(a){if(a==='backHeroes'){detail=false;$('content').scrollTop=0;renderPanel()}if(a==='exitTest'&&backup){state=backup;testMode=false;backup=null;selected='su';resetWave();changed()}if(a==='export'){let blob=new Blob([JSON.stringify(testMode?backup:state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='sunset-guard-save.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}if(a==='import')$('importfile').click();if(a==='linkAccount')toast('계정 연동은 아직 지원하지 않습니다. 저장파일 내보내기를 이용해주세요.');if(a==='logout'){if(testMode&&backup){state=backup;testMode=false;backup=null}state.session=false;save();closePanel();$('sessionGate').hidden=false;audioCtx?.suspend()}}
function validate(p){try{const validInt=(n,max)=>Number.isInteger(n)&&n>=0&&n<=max;if(p?.version!==2||!validInt(p.wave,10000)||p.wave<1||!validInt(p.best,10000)||p.best<p.wave||![p.gold,p.gems].every(n=>Number.isFinite(n)&&n>=0&&n<=1e50)||!Array.isArray(p.owned)||!p.owned.includes('su')||new Set(p.owned).size!==p.owned.length||!p.owned.every(id=>heroes.some(h=>h.id===id)&&Array.isArray(p.levels?.[id])&&p.levels[id].length===24&&p.levels[id].every(n=>validInt(n,10000))))return false;if(!Array.isArray(p.slots)||p.slots.length!==5||!p.slots.some(Boolean)||!p.slots.every(id=>id===null||p.owned.includes(id))||new Set(p.slots.filter(Boolean)).size!==p.slots.filter(Boolean).length)return false;if(!Array.isArray(p.inventory)||new Set(p.inventory).size!==p.inventory.length||!p.inventory.every(i=>items.some(x=>x.id===i))||!p.gear)return false;const equipped=[];for(const [id,eq] of Object.entries(p.gear)){if(!p.owned.includes(id)||!eq||typeof eq!=='object')return false;for(const [slot,it] of Object.entries(eq)){if(!p.inventory.includes(it)||!items.some(x=>x.id===it&&x.slot===slot)||equipped.includes(it))return false;equipped.push(it)}}return Array.isArray(p.town)&&p.town.length===4&&p.town.every(n=>validInt(n,60000))&&p.settings&&['bgm','sfx'].every(k=>Number.isFinite(p.settings[k])&&p.settings[k]>=0&&p.settings[k]<=1)&&validInt(p.pity,9)&&validInt(p.draws,10000000)&&typeof p.session==='boolean'}catch{return false}}
// Gentle procedural frontier theme and separate SFX bus. No external audio dependency.
let audioCtx=null,bgmGain=null,sfxGain=null,musicStep=0,lastShot=0;
function initAudio(){try{if(!audioCtx){audioCtx=new(window.AudioContext||window.webkitAudioContext)();bgmGain=audioCtx.createGain();sfxGain=audioCtx.createGain();bgmGain.connect(audioCtx.destination);sfxGain.connect(audioCtx.destination)}audioVolumes();if(state.session&&!document.hidden)audioCtx.resume().catch(()=>{})}catch{}}
function audioVolumes(){if(bgmGain){bgmGain.gain.value=state.settings.bgm*.11;sfxGain.gain.value=state.settings.sfx*.09}}
function tone(freq,duration,bus,type='triangle'){if(!audioCtx||audioCtx.state!=='running')return;let o=audioCtx.createOscillator(),g=audioCtx.createGain(),t=audioCtx.currentTime;o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(.001,t);g.gain.exponentialRampToValueAtTime(.4,t+.02);g.gain.exponentialRampToValueAtTime(.001,t+duration);o.connect(g);g.connect(bus);o.start(t);o.stop(t+duration+.01);o.onended=()=>{o.disconnect();g.disconnect()}}
function playSfx(kind){if(!audioCtx||document.hidden||!state.session)return;let now=performance.now();if((kind==='shot'||kind==='hit')&&now-lastShot<70)return;lastShot=now;if(kind==='shot')tone(110,.08,sfxGain,'sawtooth');else if(kind==='hit')tone(65,.16,sfxGain,'triangle');else{tone(kind==='clear'?523:392,.4,sfxGain);tone(kind==='clear'?659:494,.5,sfxGain)}}
setInterval(()=>{if(audioCtx&&state.session&&!document.hidden&&!paused&&state.settings.bgm>0){const notes=[220,0,330,392,330,0,294,0,196,0,294,330,294,0,247,0];let f=notes[musicStep++%notes.length];if(f)tone(f,.85,bgmGain)}},460);

$('content').addEventListener('click',e=>{let b=e.target.closest('button');if(!b)return;if(b.dataset.hero)selectHero(b.dataset.hero);if(b.dataset.heroTab){heroTab=b.dataset.heroTab;renderPanel()}if(b.dataset.up!==undefined)upgrade(+b.dataset.up);if(b.dataset.town!==undefined)upgradeTown(+b.dataset.town);if(b.dataset.equip)equip(b.dataset.equip);if(b.dataset.filter){equipFilter=b.dataset.filter;renderPanel()}if(b.dataset.place){let[id,i]=b.dataset.place.split(':');place(id,+i)}if(b.dataset.remove)removeHero(b.dataset.remove);if(b.dataset.buy)buy(b.dataset.buy);if(b.dataset.test)test(+b.dataset.test);if(b.dataset.action)action(b.dataset.action);if(b.dataset.formSlot){let id=state.slots[+b.dataset.formSlot];toast(id?hero(id).name+' 배치 중 · 아래 번호 버튼으로 변경':'아래 영웅의 슬롯 번호를 눌러 배치하세요.')}});
$('content').addEventListener('input',e=>{let k=e.target.dataset.volume;if(k){state.settings[k]=+e.target.value/100;$(k+'Value').textContent=e.target.value+'%';initAudio();audioVolumes();if(k==='sfx')playSfx('upgrade');save()}});
$('content').addEventListener('change',async e=>{if(e.target.id==='character'){selected=e.target.value;renderPanel()}if(e.target.id==='importfile'&&e.target.files[0]){try{if(e.target.files[0].size>1e6)throw Error();let p=migrate(JSON.parse(await e.target.files[0].text()));if(!validate(p))throw Error();state=p;state.session=true;saveRecovery=false;testMode=false;backup=null;selected='su';normalizeGear();resetWave();changed();audioVolumes();toast('저장파일을 불러왔습니다.')}catch{toast('유효한 게임 저장파일이 아닙니다. 현재 진행은 유지됩니다.')}}});
$('squad').onclick=e=>{let b=e.target.closest('[data-slot]');if(b){let id=state.slots[+b.dataset.slot];open(id?'영웅':'전투 배치');if(id)selectHero(id)}};
$('settings').onclick=()=>open('설정');$('formationLink').onclick=()=>open('전투 배치');$('close').onclick=closePanel;$('scrim').onclick=closePanel;
$('quickMenu').innerHTML=menuEntries.map(([title,,path])=>`<button class="quick-item" data-menu="${title}"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${path}"/></svg><span>${title}</span></button>`).join('');
$('quickMenu').onclick=e=>{let b=e.target.closest('[data-menu]');if(b)open(b.dataset.menu)};
$('menuToggle').onclick=()=>{let isOpen=!$('quickMenu').hidden;$('quickMenu').hidden=isOpen;$('menuToggle').setAttribute('aria-expanded',String(!isOpen))};
$('speed').onclick=()=>{speed=speed===1?2:speed===2?4:1;$('speed').textContent='속도 ×'+speed};
function togglePause(){paused=!paused;$('pause').textContent=paused?'▶ 계속하기':'Ⅱ 일시정지';hud()}
$('pause').onclick=togglePause;
$('resumeSession').onclick=()=>{state.session=true;$('sessionGate').hidden=true;initAudio();save()};
document.addEventListener('pointerdown',initAudio,{once:true});
document.addEventListener('keydown',e=>{if(e.code==='Escape'){closePanel();$('quickMenu').hidden=true;$('menuToggle').setAttribute('aria-expanded','false')}if(e.code==='Space'&&!['SELECT','INPUT','BUTTON'].includes(e.target.tagName)&&state.session){e.preventDefault();togglePause()}if(e.key==='Tab'&&!$('drawer').hidden){let focusable=[...$('drawer').querySelectorAll('button:not(:disabled),input:not([hidden]),select,summary')].filter(el=>el.offsetParent!==null),first=focusable[0],last=focusable.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}});
function normalizeGear(){for(const id of state.owned){state.gear[id]??={};let weapon=items.find(x=>x.id===state.gear[id].weapon);if(weapon&&!canEquip(id,weapon))delete state.gear[id].weapon}}
normalizeGear();
let last=performance.now(),acc=0;function loop(now){let elapsed=Math.min(.1,(now-last)/1000);last=now;if(!paused&&!document.hidden&&state.session&&assetsReady){acc+=elapsed*speed;while(acc>=1/60){update(1/60);acc-=1/60}}draw();uiTimer+=elapsed;if(uiTimer>.2){hud();refreshLiveUI();uiTimer=0}requestAnimationFrame(loop)}
document.addEventListener('visibilitychange',()=>{last=performance.now();acc=0;if(document.hidden){save();audioCtx?.suspend()}else if(state.session)audioCtx?.resume().catch(()=>{})});
window.addEventListener('beforeunload',save);setInterval(save,10000);
// Prevent stale second tabs from silently overwriting the current session.
window.addEventListener('storage',e=>{if(e.key===KEY&&!testMode&&e.newValue){saveRecovery=true;paused=true;toast('다른 창에서 진행 기록이 변경되었습니다. 새로고침하여 동기화해주세요.')}});
renderSquad();hud();$('sessionGate').hidden=state.session;requestAnimationFrame(loop);
if(saveRecovery)$('saveStatus').textContent='저장 복구 필요 · 설정에서 내보내기';
const development=new URLSearchParams(location.search).has('dev');
window.Game={get state(){return state},get enemies(){return enemies},get phase(){return phase},get baseHP(){return baseHP},get effects(){return effects},get assetsReady(){return assetsReady},stats,validate,migrate,power,sortedHeroes,test,update,resetWave,place,equip,buy,action,open,selectHero,upgrade,upgradeTown,canEquip,fire,position,actor,get upgrades(){return upgrades},get runtime(){return runtime},setBaseHP:n=>{if(testMode)baseHP=n},injectEnemies:list=>{if(testMode)enemies=list},select:id=>{if(testMode)selected=id}};

