'use strict';
/* Phase 5 — procedural combat motion, boss presentation and adaptive Canvas quality. */
(()=>{
 if(!window.Game||!window.Phase3B||!window.PixelArt)return;
 const prev={hero:PixelArt.hero,enemy:PixelArt.enemy,draw,update,spawn,hit,fire,renderPanel};
 const qualityOrder=['low','medium','high'];let autoQuality='high',fps=60,frames=0,sampleAt=performance.now(),qualityCooldown=0;
 let fx=[],bossIntro=null,shakeT=0;
 function settings(){state.settings.quality??='auto';state.settings.shake??=false;state.settings.combatFx??=true;return state.settings}
 function quality(){const q=settings().quality;return q==='auto'?autoQuality:q}
 function qualityLimit(){return quality()==='low'?28:quality()==='medium'?58:110}
 function addFx(o){if(!settings().combatFx)return;fx.push(o);if(fx.length>qualityLimit())fx.splice(0,fx.length-qualityLimit())}
 PixelArt.hero=function(g,id,attack=0,t=0){
  const f=Math.floor(t*8)%4,bob=attack?0:[0,-1,0,1][f],melee=['buck','rose'].includes(id),recoil=attack?(melee?2:-2):0;
  g.save();g.translate(recoil,bob);prev.hero(g,id,attack,t);
  if(!attack&&['june','julie'].includes(id)&&f===1){g.globalAlpha=.45;g.fillStyle=id==='julie'?'#ffe69a':'#b9e3b5';g.fillRect(5,5,3,3);g.fillRect(28,11,2,2)}
  g.restore();
 };
 PixelArt.enemy=function(g,id,t=0,boss=false){const step=Math.floor(t*6)%4,bob=[0,-1,0,1][step];g.save();g.translate(0,bob);if(boss&&step===2){g.translate(-1,0);g.scale(1.025,.985)}prev.enemy(g,id,t,boss);g.restore()};
 fire=function(id,e,ultimate=false){if(e){const p=position(id),color=ultimate?'#ffd06f':['june','julie'].includes(id)?'#bce9bd':'#fff0b0';addFx({type:ultimate?'ult':'muzzle',x:p.x+28,y:p.y-25,ex:e.x,ey:e.y-22,t:ultimate?.62:.18,max:ultimate?.62:.18,color});if(ultimate){addFx({type:'ring',x:p.x,y:p.y-28,t:.72,max:.72,color});if(settings().shake)shakeT=Math.max(shakeT,.22)}}return prev.fire(id,e,ultimate)};
 hit=function(e,damage,id,critical=false){if(!e||e.hp<=0)return prev.hit(e,damage,id,critical);const before=e.hp;prev.hit(e,damage,id,critical);if(e.hp<before){const count=quality()==='low'?2:critical?7:4;for(let i=0;i<count;i++)addFx({type:'spark',x:e.x+(Math.random()-.5)*22,y:e.y-28+(Math.random()-.5)*20,vx:(Math.random()-.5)*90,vy:-25-Math.random()*75,t:.28+Math.random()*.2,max:.48,color:critical?'#ffe082':'#e9c6a0'});if(critical&&settings().shake)shakeT=Math.max(shakeT,.1)}};
 spawn=function(){prev.spawn();const e=enemies[enemies.length-1];if(e?.boss){bossIntro={name:e.name||e.roleLabel,role:e.roleLabel,t:1.7,max:1.7};if(settings().shake)shakeT=.28}};
 function samplePerformance(){const now=performance.now();frames++;if(now-sampleAt<1800)return;fps=frames*1000/(now-sampleAt);frames=0;sampleAt=now;if(settings().quality!=='auto'||qualityCooldown>0)return;const load=enemies.length+(effects?.length||0)*.2;if(fps<42||load>42){autoQuality='low';qualityCooldown=4}else if(fps<53||load>28){autoQuality='medium';qualityCooldown=3}else if(fps>57&&load<22){autoQuality='high';qualityCooldown=3}}
 update=function(dt){prev.update(dt);qualityCooldown=Math.max(0,qualityCooldown-dt);shakeT=Math.max(0,shakeT-dt);if(bossIntro){bossIntro.t-=dt;if(bossIntro.t<=0)bossIntro=null}for(const p of fx){p.t-=dt;if(p.type==='spark'){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=150*dt}}fx=fx.filter(p=>p.t>0);const cap=quality()==='low'?42:quality()==='medium'?85:150;if(effects.length>cap)effects=effects.slice(-cap)};
 function drawFx(){for(const p of fx){const a=Math.max(0,Math.min(1,p.t/p.max));ctx.save();ctx.globalAlpha=a;if(p.type==='spark'){ctx.fillStyle=p.color;ctx.fillRect(Math.round(p.x),Math.round(p.y),quality()==='low'?2:3,quality()==='low'?2:3)}else if(p.type==='muzzle'){ctx.strokeStyle=p.color;ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(p.x+18,p.y-3);ctx.stroke()}else if(p.type==='ult'){ctx.strokeStyle=p.color;ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(p.ex,p.ey);ctx.stroke()}else if(p.type==='ring'){ctx.strokeStyle=p.color;ctx.lineWidth=4;ctx.beginPath();ctx.arc(p.x,p.y,26+(1-a)*55,0,Math.PI*2);ctx.stroke()}ctx.restore()}}
 function drawBossIntro(){if(!bossIntro)return;const progress=1-bossIntro.t/bossIntro.max,fade=Math.min(1,progress*4,bossIntro.t*2);ctx.save();ctx.globalAlpha=fade*.78;ctx.fillStyle='#091214';ctx.fillRect(0,225,1440,130);ctx.globalAlpha=fade;ctx.textAlign='center';ctx.fillStyle='#e8c77e';ctx.font='700 17px "Noto Sans KR",system-ui';ctx.fillText(bossIntro.role,720,270);ctx.fillStyle='#fff3d8';ctx.font='700 34px Georgia,"Noto Sans KR",serif';ctx.fillText(bossIntro.name,720,315);ctx.restore()}
 draw=function(){samplePerformance();ctx.imageSmoothingEnabled=false;prev.draw();drawFx();drawBossIntro();if(settings().shake&&shakeT>0){const power=Math.min(3,shakeT*10);c.style.transform=`translate(${(Math.random()-.5)*power}px,${(Math.random()-.5)*power}px)`}else c.style.transform=''};
 function fxPanel(){const s=settings(),q=quality();return `<section class="phase5-settings"><div class="sectionline"><strong>전투 연출 · 성능</strong><small>${Math.round(fps)} FPS · ${q.toUpperCase()}</small></div><p class="help">자동 품질은 프레임과 적 수를 기준으로 이펙트 수를 줄입니다. 전투 계산과 저장 데이터는 변경하지 않습니다.</p><div class="phase5-quality">${['auto','high','medium','low'].map(v=>`<button data-quality="${v}" class="${s.quality===v?'active':''}">${v==='auto'?'자동':v==='high'?'높음':v==='medium'?'중간':'낮음'}</button>`).join('')}</div><div class="row"><div><strong>전투 이펙트</strong><p>총구 화염·피격 파편·필살기 링</p></div><button data-toggle-fx class="${s.combatFx?'active':''}">${s.combatFx?'사용':'끔'}</button></div><div class="row"><div><strong>화면 흔들림</strong><p>기본값은 꺼짐 · 필살기와 보스 등장에만 적용</p></div><button data-toggle-shake class="${s.shake?'active':''}">${s.shake?'사용':'끔'}</button></div></section>`}
 renderPanel=function(){prev.renderPanel();if(!$('drawer').hidden&&tab==='설정'&&!$('content').querySelector('.phase5-settings'))$('content').insertAdjacentHTML('beforeend',fxPanel())};
 $('content').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.quality){settings().quality=b.dataset.quality;save();renderPanel()}if(b.dataset.toggleFx!==undefined){settings().combatFx=!settings().combatFx;if(!settings().combatFx)fx=[];save();renderPanel()}if(b.dataset.toggleShake!==undefined){settings().shake=!settings().shake;if(!settings().shake){shakeT=0;c.style.transform=''}save();renderPanel()}});
 settings();save();
 Game.update=update;Game.spawn=spawn;Game.fire=fire;Game.renderPanel=renderPanel;Game.phase5={get fps(){return fps},get quality(){return quality()},get effects(){return fx},settings,forceQuality:q=>{if(['auto','high','medium','low'].includes(q)){settings().quality=q;save()}},bossIntro:()=>bossIntro};window.Phase5=Game.phase5;
})();
