// Browser integration tests. Run: npm install playwright && CHROMIUM_PATH=/path/to/chrome node test.cjs
const {chromium}=require('playwright'),assert=require('node:assert/strict'),path=require('node:path');
(async()=>{let browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{}),args:['--no-sandbox','--single-process','--in-process-gpu','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-features=AudioServiceOutOfProcess,IsolateOrigins,site-per-process','--disable-dev-shm-usage','--no-zygote']});let page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('file://'+path.join(__dirname,'index.html'));await page.waitForFunction(()=>window.Game?.assetsReady&&window.Campaign&&window.AppBoot?.ready,{timeout:30000});
const checks=[];function ok(name,value){assert(value,name);checks.push(name)}
ok('5000 wave campaign metadata',await page.evaluate(()=>Game.maxWave===5000&&Campaign.acts.length===10&&Campaign.regions.length===50&&Campaign.at(5000).isFinal));
ok('launch screen shows saved front',await page.locator('#bootWave').textContent()==='WAVE 1');
await page.click('#bootStart');await page.waitForFunction(()=>document.getElementById('bootGate').hidden);
ok('game start releases battle loop',await page.evaluate(()=>!document.body.classList.contains('booting')&&!document.getElementById('bootStart').disabled));
ok('valid initial save',await page.evaluate(()=>Game.validate(Game.state)));
await page.click('#menuToggle');ok('six named menu entries',await page.locator('[data-menu]').count()===6);await page.click('[data-menu="영웅"]');await page.click('[data-hero="chel"]');ok('unowned hero is locked',await page.locator('#toast').textContent()==='해당 영웅을 아직 모집하지 않았습니다.');ok('unowned hero cannot open details',await page.locator('.hero-profile').count()===0);await page.click('[data-hero="su"]');ok('hero upgrade and equipment overview',await page.locator('.status-summary').count()===1);await page.click('[data-up="0"]');ok('upgrade consumed currency',await page.evaluate(()=>Game.state.levels.su[0]===1&&Game.state.gold===578));await page.click('#close');
const results=await page.evaluate(()=>{const g=Game,r={};g.test(1);g.state.slots=['buck',null,null,null,null];g.resetWave();const p=g.position('buck'),s=g.stats('buck');const make=x=>({x,y:p.y,hp:1000,max:1000,damage:1,speed:0,kind:0,boss:false,main:false,slow:0,burn:0,burnTime:0,stun:0,hit:0,attack:0});let a=make(p.x+40),b=make(p.x+s.range),c=make(p.x+s.range+1);g.injectEnemies([a,b,c]);g.fire('buck',a);r.tankPrimary=Math.abs(a.hp-(1000-s.atk))<1e-8;r.tankCleave=Math.abs(b.hp-(1000-s.atk*.2))<1e-8;r.tankRange=c.hp===1000;r.noBullet=g.effects.every(e=>e.type!=='line');for(let i=0;i<200;i++)g.update(1/60);r.noReload=g.runtime.buck.reload===0;g.test(1);g.state.levels.su[0]=20;let order=g.sortedHeroes();r.heroSort=order.slice(0,g.state.owned.length).every((h,i,arr)=>i===0||g.power(arr[i-1].id)>=g.power(h.id));g.select('buck');g.equip('iron');r.weaponRole=!g.state.gear.buck.weapon;g.equip('mace');r.maceEquipped=g.state.gear.buck.weapon==='mace';g.place('buck',0);r.uniqueSlots=new Set(g.state.slots.filter(Boolean)).size===g.state.slots.filter(Boolean).length;let hp=g.baseHP;g.upgradeTown(0);r.town= g.state.town[0]===1&&g.baseHP===hp+35;g.state.pity=9;g.state.owned=['su'];g.state.slots=['su',null,null,null,null];g.buy('hero');r.pity=g.state.owned.length===2&&g.state.pity===0;g.test(100);for(let i=0;i<1300;i++)g.update(1/60);r.mainBoss=g.enemies.some(e=>e.boss&&e.main);g.setBaseHP(0);g.update(.02);r.fail=g.phase==='fail';let w=g.state.wave;for(let i=0;i<185;i++)g.update(1/60);r.retry=g.phase==='fight'&&g.state.wave===w;g.action('exitTest');r.restored=g.state.owned.length===1&&g.state.levels.su[0]===1;let old=JSON.parse(JSON.stringify(g.state));old.version=1;old.levels.su[18]=2;old.levels.su[19]=3;delete old.town;delete old.settings;delete old.pity;delete old.session;let migrated=g.migrate(old);r.migration=g.validate(migrated)&&migrated.town[0]===2&&migrated.town[1]===3&&migrated.levels.su[18]===0;r.rejectSave=!g.validate({...g.state,slots:['su','su',null,null,null]});r.finalRegion=g.campaignAt(5000).chapter===50&&g.campaignAt(5000).act===10;return r});for(let [k,v]of Object.entries(results))ok(k,v);
await page.click('#settings');await page.locator('[data-volume="bgm"]').fill('0');ok('BGM volume live',await page.evaluate(()=>Game.state.settings.bgm===0));await page.locator('[data-volume="sfx"]').fill('20');ok('SFX volume live',await page.evaluate(()=>Game.state.settings.sfx===.2));await page.click('[data-action="logout"]');ok('logout gates session',await page.locator('#sessionGate').isVisible());await page.click('#resumeSession');ok('resume preserves progress',await page.evaluate(()=>Game.state.levels.su[0]===1&&Game.state.session));await page.reload();await page.waitForFunction(()=>window.Game?.assetsReady&&window.AppBoot?.ready);ok('launch gate returns after reload',await page.locator('#bootGate').isVisible());await page.click('#bootStart');await page.waitForFunction(()=>document.getElementById('bootGate').hidden);ok('save reload persists settings',await page.evaluate(()=>Game.state.settings.bgm===0&&Game.state.settings.sfx===.2));
for(const size of [{width:844,height:390},{width:390,height:844}]){await page.setViewportSize(size);await page.click('#menuToggle');await page.click('[data-menu="영웅"]');await page.waitForTimeout(250);ok('responsive dialog '+size.width,await page.evaluate(()=>{let r=document.getElementById('drawer').getBoundingClientRect();return r.left>=0&&r.right<=innerWidth&&r.bottom<=innerHeight}));await page.click('#close')}
ok('no browser errors',errors.length===0);console.log(JSON.stringify({passed:checks.length,checks,errors},null,2));await browser.close()})().catch(e=>{console.error(e);process.exit(1)});
