// Browser integration tests. Run: npm install playwright && CHROMIUM_PATH=/path/to/chrome node test.cjs
const {chromium}=require('playwright'),assert=require('node:assert/strict'),path=require('node:path');
(async()=>{let browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{}),args:['--no-sandbox','--single-process','--in-process-gpu','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-features=AudioServiceOutOfProcess,IsolateOrigins,site-per-process','--disable-dev-shm-usage','--no-zygote']});let page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('file://'+path.join(__dirname,'index.html'));await page.waitForFunction(()=>window.Game?.assetsReady&&window.Campaign&&window.Phase2Content&&window.Phase2Art&&window.HeroV3&&window.EquipmentV3&&window.AppBoot?.ready,{timeout:30000});
const checks=[];function ok(name,value){assert(value,name);checks.push(name)}
ok('5000 wave campaign metadata',await page.evaluate(()=>Game.maxWave===5000&&Campaign.acts.length===10&&Campaign.regions.length===50&&Campaign.at(5000).isFinal));
ok('phase 2 content registered',await page.evaluate(()=>Game.phase2&&Phase2Content.archetypes.length===10&&Game.testWaves.includes(5000)));
ok('seven hero v3 reference active',await page.evaluate(()=>Game.state.version===3&&HeroV3.roster.length===7&&HeroV3.roster.map(h=>h.name).join(',')==='낸시,루나,엘로나,제시,줄리,첼리,티나'));
ok('eight equipment slots active',await page.evaluate(()=>Object.keys(EquipmentV3.slots).length===8&&EquipmentV3.slots.outfit==='한벌 옷'&&EquipmentV3.slots.ring2==='반지 2'));
ok('launch screen shows saved front',await page.locator('#bootWave').textContent()==='WAVE 1');
await page.click('#bootStart');await page.waitForFunction(()=>document.getElementById('bootGate').hidden);
ok('game start releases battle loop',await page.evaluate(()=>!document.body.classList.contains('booting')&&!document.getElementById('bootStart').disabled));
ok('valid initial save',await page.evaluate(()=>Game.validate(Game.state)));
await page.click('#menuToggle');ok('six named menu entries',await page.locator('[data-menu]').count()===6);await page.click('[data-menu="영웅"]');await page.click('[data-hero="chel"]');ok('unowned hero is locked',await page.locator('#toast').textContent()==='해당 영웅을 아직 모집하지 않았습니다.');ok('unowned hero cannot open details',await page.locator('.hero-profile').count()===0);await page.click('[data-hero="su"]');ok('hero upgrade and equipment overview',await page.locator('.status-summary').count()===1);ok('phase 3 bulk upgrade selector shown',await page.locator('[data-phase3-hero="10"]').count()===1);await page.click('[data-hero-tab="장착 장비"]');ok('eight-slot paperdoll shown',await page.locator('.paperdoll [data-v3-gear-slot]').count()===8);await page.click('[data-hero-tab="성장"]');await page.click('[data-up="0"]');ok('upgrade consumed currency',await page.evaluate(()=>Game.state.levels.su[0]===1&&Game.state.gold===578));await page.click('#close');
const results=await page.evaluate(()=>{const g=Game,r={};g.test(1);r.julieOwned=g.state.owned.includes('julie')&&g.state.version===3;g.heroV3.autoFormation();r.autoFormation=g.state.slots.filter(Boolean).length===5&&new Set(g.state.slots.filter(Boolean)).size===5&&g.state.slots.includes('buck');g.heroV3.setHeroUpgradeAmount(10);g.select('su');g.state.gold=1e9;let lv=g.state.levels.su[0];g.upgrade(0);r.bulkUpgrade=g.state.levels.su[0]===lv+10;g.heroV3.setHeroUpgradeAmount(1);
 g.test(1);g.state.slots=['buck',null,null,null,null];g.resetWave();const p=g.position('buck'),s=g.stats('buck');const make=x=>({x,y:p.y,hp:1000,max:1000,damage:1,speed:0,kind:0,boss:false,main:false,slow:0,burn:0,burnTime:0,stun:0,hit:0,attack:0});let a=make(p.x+40),b=make(p.x+s.range),c=make(p.x+s.range+1);g.injectEnemies([a,b,c]);g.fire('buck',a);r.tankPrimary=Math.abs(a.hp-(1000-s.atk))<1e-8;r.tankCleave=Math.abs(b.hp-(1000-s.atk*.2))<1e-8;r.tankRange=c.hp===1000;r.noBullet=g.effects.every(e=>e.type!=='line');for(let i=0;i<200;i++)g.update(1/60);r.noReload=g.runtime.buck.reload===0;g.test(1);g.state.levels.su[0]=20;let order=g.sortedHeroes();r.heroSort=order.slice(0,g.state.owned.length).every((h,i,arr)=>i===0||g.power(arr[i-1].id)>=g.power(h.id));g.select('buck');g.equip('iron');r.weaponRole=!g.state.gear.buck.weapon;g.equip('mace');r.maceEquipped=g.state.gear.buck.weapon==='mace';g.place('buck',0);r.uniqueSlots=new Set(g.state.slots.filter(Boolean)).size===g.state.slots.filter(Boolean).length;let hp=g.baseHP;g.upgradeTown(0);r.town=g.state.town[0]===1&&g.baseHP===hp+35;g.state.pity=9;g.state.owned=['su'];g.state.slots=['su',null,null,null,null];g.buy('hero');r.pity=g.state.owned.length===2&&g.state.pity===0;
 g.test(500);g.resetWave();g.spawn();let act1=g.enemies.at(-1);r.phase2Enemy=!!act1?.archetype&&act1.artId.startsWith('act1-');for(let i=1;i<30&&!g.enemies.some(e=>e.boss);i++)g.spawn();let actBoss=g.enemies.find(e=>e.boss);r.actBoss=!!actBoss?.actBoss&&actBoss.shield>0&&actBoss.roleLabel==='ACT BOSS';
 g.test(1500);g.resetWave();g.spawn();let act3=g.enemies.at(-1);r.actRouting=Campaign.at(1500).act===3&&act3.act===3&&act3.artId.startsWith('act3-');
 g.test(4000);g.resetWave();g.spawn();let act8=g.enemies.at(-1);r.lateAct=Campaign.at(4000).act===8&&!!act8.archetype;
 g.test(100);for(let i=0;i<1300;i++)g.update(1/60);r.mainBoss=g.enemies.some(e=>e.boss&&e.main);g.setBaseHP(0);g.update(.02);r.fail=g.phase==='fail';let w=g.state.wave;for(let i=0;i<185;i++)g.update(1/60);r.retry=g.phase==='fight'&&g.state.wave===w;g.action('exitTest');r.restored=g.state.owned.length===1&&g.state.levels.su[0]===1&&g.state.version===3;let old=JSON.parse(JSON.stringify(g.state));old.version=1;old.levels.su[18]=2;old.levels.su[19]=3;delete old.town;delete old.settings;delete old.pity;delete old.session;let migrated=g.migrate(old);r.migration=g.validate(migrated)&&migrated.version===3&&migrated.town[0]===2&&migrated.town[1]===3&&migrated.levels.su[18]===0;r.rejectSave=!g.validate({...g.state,slots:['su','su',null,null,null]});r.finalRegion=g.campaignAt(5000).chapter===50&&g.campaignAt(5000).act===10;g.save();let v2=JSON.parse(localStorage.getItem('sunset-guard-v2')),v3=JSON.parse(localStorage.getItem('sunset-guard-v3-seven'));r.dualSave=v2.version===2&&v3.version===3&&!v2.owned.includes('julie');return r});for(let [k,v]of Object.entries(results))ok(k,v);
await page.click('#settings');ok('full campaign QA checkpoints shown',await page.locator('[data-test="5000"]').count()===1);ok('phase 3 progression panel shown',await page.locator('.phase3-progress').count()===1);await page.locator('[data-volume="bgm"]').fill('0');ok('BGM volume live',await page.evaluate(()=>Game.state.settings.bgm===0));await page.locator('[data-volume="sfx"]').fill('20');ok('SFX volume live',await page.evaluate(()=>Game.state.settings.sfx===.2));await page.click('[data-action="logout"]');ok('logout gates session',await page.locator('#sessionGate').isVisible());await page.click('#resumeSession');ok('resume preserves progress',await page.evaluate(()=>Game.state.levels.su[0]===1&&Game.state.session));await page.reload();await page.waitForFunction(()=>window.Game?.assetsReady&&window.Phase2Content&&window.HeroV3&&window.EquipmentV3&&window.AppBoot?.ready);ok('launch gate returns after reload',await page.locator('#bootGate').isVisible());await page.click('#bootStart');await page.waitForFunction(()=>document.getElementById('bootGate').hidden);ok('v3 save reload persists settings',await page.evaluate(()=>Game.state.version===3&&Game.state.settings.bgm===0&&Game.state.settings.sfx===.2));
for(const size of [{width:844,height:390},{width:390,height:844}]){await page.setViewportSize(size);await page.click('#menuToggle');await page.click('[data-menu="영웅"]');await page.waitForTimeout(250);ok('responsive dialog '+size.width,await page.evaluate(()=>{let r=document.getElementById('drawer').getBoundingClientRect();return r.left>=0&&r.right<=innerWidth&&r.bottom<=innerHeight}));await page.click('#close')}
ok('no browser errors',errors.length===0);console.log(JSON.stringify({passed:checks.length,checks,errors},null,2));await browser.close()})().catch(e=>{console.error(e);process.exit(1)});
